// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vencmgdjtmjkbceusdiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbmNtZ2RqdG1qa2JjZXVzZGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTg2NDksImV4cCI6MjA1NjI5NDY0OX0.a5n-6ApTcFPLNIKNZw6lBpW5K_a144FgV6gpxcUaSxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});